@startuml
'https://plantuml.com/class-diagram

top to bottom direction

package "Runtime" {
    class SimuServer {
        - SimuServer : _server
        - RequestHandler: _handler
        - RouteHandler : _router
        + SimuServer(RequestHandler : handler, RouteHandler : router)
        + Setup(HttpMethod : method, string : path) : SimuServerBuilder
    }
    
    class RouteHandler {
        + List<RouteRule> Routes  
    }
    
    class Route {
        + HttpMethod : Method
        + string : Path
        
        + Route(HttpMethod : method, string : path)
    }
    
    class RouteRule {
        + Route : Route
        + func<SimuRequest, SimuResponse> Handler
    }
    
    
    class SimuRequest {
        + string : Path
        + HttpMethod : Method
    }
    
    class RequestHandler {
        + Handle(HttpListenerContext context) : SimuResponse
    }
    
    class SimuResponse {
        + int : StatusCode
        + string : Body
        
        + SimuResponse(int : status, string : body)
    }
}

package "Builder API" {
    class SimuServerBuilder {
        + SimuServer : Server
        + SetupBuilder(HttpMethod : method, string path) : RouteRuleBuilder
    }
    
    class RouteRuleBuilder {
        - SimuServerBuilder : _serverBuilder
        - RouteRule : _routeRule
        
        + Responds(func<Request, Response> func) : RouteRuleBuilder
        + End() : SimuServerBuilder
    }
}

SimuServer --* SimuServerBuilder
RouteRuleBuilder *-- SimuServerBuilder

RouteRuleBuilder *-- RouteRule
RouteRule *-- Route

SimuServer *-- RequestHandler
SimuServer *-- RouteHandler

RouteHandler o-- RouteRule

@enduml